### PR TITLE
Explicitly set logging level to INFO

### PR DESCRIPTION
**Pull request by skalermo**
I had a problem with logging: it didn't output anything neither locally, nor in cloud. This code fixed that.

### CODE REVIEW

**Comment by skalermo** [comment]
@zdoryk Can you take a look?

**Review by zdoryk — COMMENTED** [review]
I mean, it's weird, will check it when will be with my laptop in a while. Usually I create my own logger class to use but here I wanted to simplify the process. Will check in hour or two

**Comment by zdoryk** [comment]
Did this really fix the issue for you yesterday? I've tried to add this line but still do not see logs through logging module. 

For this code
``` Pyhton
def main():
    logging.getLogger().setLevel(logging.INFO)
    logging.info("Logging with fix proposed in PR")
    print("Usual print\n\n")
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)    
    logger.info("Logger Object")
    
    root = logging.getLogger()
    root.setLevel(logging.INFO)

    handler = logging.StreamHandler(sys.stdout)
    handler.setLevel(logging.INFO)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    root.addHandler(handler)
    root.info("Sys stdout")
    root.info("Sys stdout")
```

I have this logs:
obraz

So the easiest way to go rn it's just use print statements instead of using logging module, cause as you see this code:
```
    handler = logging.StreamHandler(sys.stdout)
    handler.setLevel(logging.INFO)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    root.addHandler(handler)
    root.info("Sys stdout")
    root.info("Sys stdout")
```
Will make all of the logs inside one row in CloudWatch, but it's up to you, you can use sys module + logging together instead of print. 
Regarding your approach, as you see from my code snippet and screenshot, it's not working for me, can yoou please provide screenshot + code snippet of how it works for you?

**Comment by skalermo** [comment]
Just rebuilt infrastructure and invoked raw lambda function as in this PR. 

Screenshot below shows the logs from CloudWatch. There is clearly user-defined log entry, though not listed separately like in your example.
image

**Comment by skalermo** [comment]
I 'stole' logger setting from [here](https://stackoverflow.com/a/56579088), maybe that'll help.

**Comment by zdoryk** [comment]
@skalermo I've checked this for lambdas, and for lambdas this works, so thank you, will merge this PR. BTW I've checked the work that you've done so far - very good and clean code, will wait for glue_enriched as well :D

**Pull request merged**
